name: Release Plugin

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build package
        run: python build_package.py

      - name: Extract version
        id: vars
        run: |
          MANIFEST_VERSION=$(grep '^version:' manifest.yaml | awk '{print $2}')
          TAG_VERSION=${GITHUB_REF##*/}
          # Strip leading v from tag
          TAG_VERSION_STRIPPED=${TAG_VERSION#v}
          # Prefer manifest version; ensure consistency
          if [ "$MANIFEST_VERSION" != "$TAG_VERSION_STRIPPED" ]; then
            echo "Warning: manifest.yaml version ($MANIFEST_VERSION) does not match tag ($TAG_VERSION_STRIPPED)." >&2
          fi
          echo "version=$MANIFEST_VERSION" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: botos3-${{ steps.vars.outputs.version }}
          path: dist/botos3-${{ steps.vars.outputs.version }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/botos3-${{ steps.vars.outputs.version }}.zip
          name: botos3 ${{ steps.vars.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
